group = 'com.sriannamalai.mdviewer'
version = '0.0.1'

buildscript {
    repositories { google(); mavenCentral() }
    dependencies { classpath 'com.android.tools.build:gradle:9.0.1' }
}

apply plugin: 'com.android.library'

android {
    namespace = 'com.sriannamalai.mdviewer'
    compileSdk = 36
    defaultConfig { minSdk = 24 }
    sourceSets { main { jniLibs.srcDirs = ['src/main/jniLibs'] } }
}
